dist: trusty
sudo: false
language: cpp
matrix:
  include:
  - compiler: gcc
    env: ENABLE_COVERAGE=true
  - compiler: clang
    env: ENABLE_COVERAGE=false
before_install:
  - export APPS_DIR=${HOME}/apps
  - export LCOV_ROOT_DIR=${APPS_DIR}/lcov
  - export CMAKE_ROOT_DIR=${APPS_DIR}/cmake
install: ./.travis/install.sh
before_script:
  - export PATH="${CMAKE_ROOT_DIR}/bin:$PATH"
  - export PATH="${LCOV_ROOT_DIR}/bin:$PATH"
script: ./.travis/run-script.sh
after_success:
  - if [ "${ENABLE_COVERAGE}" = true ]; then coveralls-lcov --repo-token ${COVERALLS_TOKEN} ${TRAVIS_BUILD_DIR}/build/coverage-all.info; fi
