sudo: false
dist: trusty
language: cpp
branches:
  only:
  - ci-test
addons:
  apt:
    sources:
      - george-edison55/cmake-3.x
    packages:
      - cmake
compiler:
  - gcc
script:
  - mkdir install && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX="../install" -DCMAKE_BUILD_TYPE=debug -DWITH_TESTS=ON ..
  - make all
  - make test
  - make install