language: cpp
branches:
  only:
  - ci-test
install:
  - sudo apt-get update -qq
script:
  - mkdir install && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX ../install -DCMAKE_BUILD_TYPE=Release .. -DWITH_TESTS=ON && make all test install